// Auto-generated by scripts/generate.ts — DO NOT EDIT
import type { ComponentType, SVGProps } from "react";

import { BrandsFacebookIcon } from "./icons/BrandsFacebook";
import { BrandsGithubIcon } from "./icons/BrandsGithub";
import { BrandsInstagramIcon } from "./icons/BrandsInstagram";
import { BrandsLinkedinIcon } from "./icons/BrandsLinkedin";
import { BrandsNpmIcon } from "./icons/BrandsNpm";
import { OutlineBookmarkIcon } from "./icons/OutlineBookmark";
import { OutlineCartIcon } from "./icons/OutlineCart";
import { OutlineMinusCircleIcon } from "./icons/OutlineMinusCircle";
import { OutlinePlusCircleIcon } from "./icons/OutlinePlusCircle";
import { OutlineStoreIcon } from "./icons/OutlineStore";
import { OutlineTruckIcon } from "./icons/OutlineTruck";
import { OutlineWarehouseIcon } from "./icons/OutlineWarehouse";
import { SolidArrowDownZAIcon } from "./icons/SolidArrowDownZA";
import { SolidArrowLeftIcon } from "./icons/SolidArrowLeft";
import { SolidArrowRightLongIcon } from "./icons/SolidArrowRightLong";
import { SolidArrowRightIcon } from "./icons/SolidArrowRight";
import { SolidArrowUpAZIcon } from "./icons/SolidArrowUpAZ";
import { SolidBanIcon } from "./icons/SolidBan";
import { SolidBarsIcon } from "./icons/SolidBars";
import { SolidBellIcon } from "./icons/SolidBell";
import { SolidBookmarkIcon } from "./icons/SolidBookmark";
import { SolidBoxArchiveIcon } from "./icons/SolidBoxArchive";
import { SolidBoxDownIcon } from "./icons/SolidBoxDown";
import { SolidBoxUpIcon } from "./icons/SolidBoxUp";
import { SolidBoxesIcon } from "./icons/SolidBoxes";
import { SolidCalendarDotsIcon } from "./icons/SolidCalendarDots";
import { SolidCalendarIcon } from "./icons/SolidCalendar";
import { SolidCartIcon } from "./icons/SolidCart";
import { SolidCashierIcon } from "./icons/SolidCashier";
import { SolidCcIcon } from "./icons/SolidCc";
import { SolidChartIcon } from "./icons/SolidChart";
import { SolidChartdIcon } from "./icons/SolidChartd";
import { SolidChartpIcon } from "./icons/SolidChartp";
import { SolidCheckIcon } from "./icons/SolidCheck";
import { SolidChecksIcon } from "./icons/SolidChecks";
import { SolidChevronDownIcon } from "./icons/SolidChevronDown";
import { SolidChevronLeftIcon } from "./icons/SolidChevronLeft";
import { SolidChevronRightIcon } from "./icons/SolidChevronRight";
import { SolidChevronUpIcon } from "./icons/SolidChevronUp";
import { SolidClipboardCheckIcon } from "./icons/SolidClipboardCheck";
import { SolidClipboardIcon } from "./icons/SolidClipboard";
import { SolidCogIcon } from "./icons/SolidCog";
import { SolidCopyIcon } from "./icons/SolidCopy";
import { SolidCrosshairsIcon } from "./icons/SolidCrosshairs";
import { SolidDollarIcon } from "./icons/SolidDollar";
import { SolidDotsIcon } from "./icons/SolidDots";
import { SolidDotsvIcon } from "./icons/SolidDotsv";
import { SolidEditIcon } from "./icons/SolidEdit";
import { SolidEllipsisHIcon } from "./icons/SolidEllipsisH";
import { SolidEllipsisVIcon } from "./icons/SolidEllipsisV";
import { SolidEnvelopeIcon } from "./icons/SolidEnvelope";
import { SolidExclamationCircleIcon } from "./icons/SolidExclamationCircle";
import { SolidExclamationTriangleIcon } from "./icons/SolidExclamationTriangle";
import { SolidExpandIcon } from "./icons/SolidExpand";
import { SolidExportIcon } from "./icons/SolidExport";
import { SolidEyeLowVisionIcon } from "./icons/SolidEyeLowVision";
import { SolidEyeOffIcon } from "./icons/SolidEyeOff";
import { SolidEyeIcon } from "./icons/SolidEye";
import { SolidFileExcelIcon } from "./icons/SolidFileExcel";
import { SolidFileImageIcon } from "./icons/SolidFileImage";
import { SolidFilePdfIcon } from "./icons/SolidFilePdf";
import { SolidFileTextIcon } from "./icons/SolidFileText";
import { SolidFileWordIcon } from "./icons/SolidFileWord";
import { SolidFileIcon } from "./icons/SolidFile";
import { SolidHandHoldingIcon } from "./icons/SolidHandHolding";
import { SolidHistoryIcon } from "./icons/SolidHistory";
import { SolidHomeIcon } from "./icons/SolidHome";
import { SolidImageIcon } from "./icons/SolidImage";
import { SolidImagesIcon } from "./icons/SolidImages";
import { SolidImportIcon } from "./icons/SolidImport";
import { SolidKeyIcon } from "./icons/SolidKey";
import { SolidLineChartIcon } from "./icons/SolidLineChart";
import { SolidLinkIcon } from "./icons/SolidLink";
import { SolidListCheckIcon } from "./icons/SolidListCheck";
import { SolidMagnifyingGlassIcon } from "./icons/SolidMagnifyingGlass";
import { SolidMinusIcon } from "./icons/SolidMinus";
import { SolidMoneyIcon } from "./icons/SolidMoney";
import { SolidMoneysIcon } from "./icons/SolidMoneys";
import { SolidMoneytIcon } from "./icons/SolidMoneyt";
import { SolidPlusIcon } from "./icons/SolidPlus";
import { SolidPowerOffIcon } from "./icons/SolidPowerOff";
import { SolidQuestionCircleIcon } from "./icons/SolidQuestionCircle";
import { SolidQuestionIcon } from "./icons/SolidQuestion";
import { SolidReceiptIcon } from "./icons/SolidReceipt";
import { SolidRefreshIcon } from "./icons/SolidRefresh";
import { SolidReportIcon } from "./icons/SolidReport";
import { SolidRotateIcon } from "./icons/SolidRotate";
import { SolidSackDollarIcon } from "./icons/SolidSackDollar";
import { SolidSaveIcon } from "./icons/SolidSave";
import { SolidSearchIcon } from "./icons/SolidSearch";
import { SolidSidebarIcon } from "./icons/SolidSidebar";
import { SolidSigninIcon } from "./icons/SolidSignin";
import { SolidSlidersIcon } from "./icons/SolidSliders";
import { SolidSortAscIcon } from "./icons/SolidSortAsc";
import { SolidSortDescIcon } from "./icons/SolidSortDesc";
import { SolidSortIcon } from "./icons/SolidSort";
import { SolidStarOfLifeIcon } from "./icons/SolidStarOfLife";
import { SolidStarIcon } from "./icons/SolidStar";
import { SolidStoreIcon } from "./icons/SolidStore";
import { SolidTimesIcon } from "./icons/SolidTimes";
import { SolidTrashIcon } from "./icons/SolidTrash";
import { SolidTruckIcon } from "./icons/SolidTruck";
import { SolidUserCircleIcon } from "./icons/SolidUserCircle";
import { SolidUserCogIcon } from "./icons/SolidUserCog";
import { SolidUserEditIcon } from "./icons/SolidUserEdit";
import { SolidUserIcon } from "./icons/SolidUser";
import { SolidUsersContainerIcon } from "./icons/SolidUsersContainer";
import { SolidUsersIcon } from "./icons/SolidUsers";
import { SolidWarehouseIcon } from "./icons/SolidWarehouse";
import { SolidWrenchIcon } from "./icons/SolidWrench";

export const iconRegistry = {
  "brands/facebook": BrandsFacebookIcon,
  "brands/github": BrandsGithubIcon,
  "brands/instagram": BrandsInstagramIcon,
  "brands/linkedin": BrandsLinkedinIcon,
  "brands/npm": BrandsNpmIcon,
  "outline/bookmark": OutlineBookmarkIcon,
  "outline/cart": OutlineCartIcon,
  "outline/minus-circle": OutlineMinusCircleIcon,
  "outline/plus-circle": OutlinePlusCircleIcon,
  "outline/store": OutlineStoreIcon,
  "outline/truck": OutlineTruckIcon,
  "outline/warehouse": OutlineWarehouseIcon,
  "solid/arrow-down-z-a": SolidArrowDownZAIcon,
  "solid/arrow-left": SolidArrowLeftIcon,
  "solid/arrow-right-long": SolidArrowRightLongIcon,
  "solid/arrow-right": SolidArrowRightIcon,
  "solid/arrow-up-a-z": SolidArrowUpAZIcon,
  "solid/ban": SolidBanIcon,
  "solid/bars": SolidBarsIcon,
  "solid/bell": SolidBellIcon,
  "solid/bookmark": SolidBookmarkIcon,
  "solid/box-archive": SolidBoxArchiveIcon,
  "solid/box-down": SolidBoxDownIcon,
  "solid/box-up": SolidBoxUpIcon,
  "solid/boxes": SolidBoxesIcon,
  "solid/calendar-dots": SolidCalendarDotsIcon,
  "solid/calendar": SolidCalendarIcon,
  "solid/cart": SolidCartIcon,
  "solid/cashier": SolidCashierIcon,
  "solid/cc": SolidCcIcon,
  "solid/chart": SolidChartIcon,
  "solid/chartd": SolidChartdIcon,
  "solid/chartp": SolidChartpIcon,
  "solid/check": SolidCheckIcon,
  "solid/checks": SolidChecksIcon,
  "solid/chevron-down": SolidChevronDownIcon,
  "solid/chevron-left": SolidChevronLeftIcon,
  "solid/chevron-right": SolidChevronRightIcon,
  "solid/chevron-up": SolidChevronUpIcon,
  "solid/clipboard-check": SolidClipboardCheckIcon,
  "solid/clipboard": SolidClipboardIcon,
  "solid/cog": SolidCogIcon,
  "solid/copy": SolidCopyIcon,
  "solid/crosshairs": SolidCrosshairsIcon,
  "solid/dollar": SolidDollarIcon,
  "solid/dots": SolidDotsIcon,
  "solid/dotsv": SolidDotsvIcon,
  "solid/edit": SolidEditIcon,
  "solid/ellipsis-h": SolidEllipsisHIcon,
  "solid/ellipsis-v": SolidEllipsisVIcon,
  "solid/envelope": SolidEnvelopeIcon,
  "solid/exclamation-circle": SolidExclamationCircleIcon,
  "solid/exclamation-triangle": SolidExclamationTriangleIcon,
  "solid/expand": SolidExpandIcon,
  "solid/export": SolidExportIcon,
  "solid/eye-low-vision": SolidEyeLowVisionIcon,
  "solid/eye-off": SolidEyeOffIcon,
  "solid/eye": SolidEyeIcon,
  "solid/file-excel": SolidFileExcelIcon,
  "solid/file-image": SolidFileImageIcon,
  "solid/file-pdf": SolidFilePdfIcon,
  "solid/file-text": SolidFileTextIcon,
  "solid/file-word": SolidFileWordIcon,
  "solid/file": SolidFileIcon,
  "solid/hand-holding": SolidHandHoldingIcon,
  "solid/history": SolidHistoryIcon,
  "solid/home": SolidHomeIcon,
  "solid/image": SolidImageIcon,
  "solid/images": SolidImagesIcon,
  "solid/import": SolidImportIcon,
  "solid/key": SolidKeyIcon,
  "solid/line-chart": SolidLineChartIcon,
  "solid/link": SolidLinkIcon,
  "solid/list-check": SolidListCheckIcon,
  "solid/magnifying-glass": SolidMagnifyingGlassIcon,
  "solid/minus": SolidMinusIcon,
  "solid/money": SolidMoneyIcon,
  "solid/moneys": SolidMoneysIcon,
  "solid/moneyt": SolidMoneytIcon,
  "solid/plus": SolidPlusIcon,
  "solid/power-off": SolidPowerOffIcon,
  "solid/question-circle": SolidQuestionCircleIcon,
  "solid/question": SolidQuestionIcon,
  "solid/receipt": SolidReceiptIcon,
  "solid/refresh": SolidRefreshIcon,
  "solid/report": SolidReportIcon,
  "solid/rotate": SolidRotateIcon,
  "solid/sack-dollar": SolidSackDollarIcon,
  "solid/save": SolidSaveIcon,
  "solid/search": SolidSearchIcon,
  "solid/sidebar": SolidSidebarIcon,
  "solid/signin": SolidSigninIcon,
  "solid/sliders": SolidSlidersIcon,
  "solid/sort-asc": SolidSortAscIcon,
  "solid/sort-desc": SolidSortDescIcon,
  "solid/sort": SolidSortIcon,
  "solid/star-of-life": SolidStarOfLifeIcon,
  "solid/star": SolidStarIcon,
  "solid/store": SolidStoreIcon,
  "solid/times": SolidTimesIcon,
  "solid/trash": SolidTrashIcon,
  "solid/truck": SolidTruckIcon,
  "solid/user-circle": SolidUserCircleIcon,
  "solid/user-cog": SolidUserCogIcon,
  "solid/user-edit": SolidUserEditIcon,
  "solid/user": SolidUserIcon,
  "solid/users-container": SolidUsersContainerIcon,
  "solid/users": SolidUsersIcon,
  "solid/warehouse": SolidWarehouseIcon,
  "solid/wrench": SolidWrenchIcon,
} as const;

export type IconName = keyof typeof iconRegistry;

export type IconComponent = ComponentType<SVGProps<SVGSVGElement>>;
